"""
Plot OSI Distribution from Tuning Statistics

This script reads the tuning_statistics.csv generated by GratingTuningCurve.py
and creates a distribution plot of Orientation Selectivity Index (OSI) values.
"""
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import argparse


def plot_osi_distribution(csv_path, save_path=None):
    """
    Read tuning statistics CSV and plot OSI distribution.

    Args:
        csv_path: Path to tuning_statistics.csv file
        save_path: Optional path to save the plot (default: same folder as CSV)
    """
    csv_path = Path(csv_path)

    # Read the CSV file
    print(f"Reading tuning statistics from: {csv_path}")
    df = pd.read_csv(csv_path)

    print(f"Loaded {len(df)} units")
    print(f"OSI range: {df['osi'].min():.3f} - {df['osi'].max():.3f}")
    print(f"OSI mean: {df['osi'].mean():.3f} ± {df['osi'].std():.3f}")

    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('Orientation Selectivity Index (OSI) Distribution',
                 fontsize=16, fontweight='bold')

    # 1. Histogram with density curve
    ax1 = axes[0, 0]
    n, bins, patches = ax1.hist(df['osi'], bins=30, density=True,
                                 alpha=0.7, color='#2E86AB', edgecolor='black')

    # Add KDE (kernel density estimate)
    from scipy.stats import gaussian_kde
    kde = gaussian_kde(df['osi'])
    x_range = np.linspace(df['osi'].min(), df['osi'].max(), 200)
    ax1.plot(x_range, kde(x_range), 'r-', linewidth=2, label='KDE')

    # Add mean and median lines
    mean_osi = df['osi'].mean()
    median_osi = df['osi'].median()
    ax1.axvline(mean_osi, color='green', linestyle='--', linewidth=2,
                label=f'Mean: {mean_osi:.3f}')
    ax1.axvline(median_osi, color='orange', linestyle='--', linewidth=2,
                label=f'Median: {median_osi:.3f}')

    ax1.set_xlabel('OSI', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Density', fontsize=12, fontweight='bold')
    ax1.set_title('OSI Distribution (Histogram + KDE)', fontsize=13, fontweight='bold')
    ax1.legend(fontsize=10)
    ax1.grid(True, alpha=0.3)

    # 2. Cumulative distribution
    ax2 = axes[0, 1]
    sorted_osi = np.sort(df['osi'])
    cumulative = np.arange(1, len(sorted_osi) + 1) / len(sorted_osi)
    ax2.plot(sorted_osi, cumulative, linewidth=2, color='#2E86AB')
    ax2.axhline(0.5, color='orange', linestyle='--', linewidth=1.5,
                label=f'Median: {median_osi:.3f}')
    ax2.axvline(median_osi, color='orange', linestyle='--', linewidth=1.5)

    # Add quartiles
    q25 = df['osi'].quantile(0.25)
    q75 = df['osi'].quantile(0.75)
    ax2.axvline(q25, color='gray', linestyle=':', linewidth=1.5,
                label=f'Q1: {q25:.3f}')
    ax2.axvline(q75, color='gray', linestyle=':', linewidth=1.5,
                label=f'Q3: {q75:.3f}')

    ax2.set_xlabel('OSI', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Cumulative Probability', fontsize=12, fontweight='bold')
    ax2.set_title('Cumulative Distribution', fontsize=13, fontweight='bold')
    ax2.legend(fontsize=10)
    ax2.grid(True, alpha=0.3)

    # 3. Box plot and violin plot
    ax3 = axes[1, 0]

    # Create violin plot
    parts = ax3.violinplot([df['osi']], positions=[1], widths=0.7,
                           showmeans=True, showmedians=True)

    # Color the violin
    for pc in parts['bodies']:
        pc.set_facecolor('#2E86AB')
        pc.set_alpha(0.7)

    # Overlay strip plot for individual points
    np.random.seed(42)
    y_jitter = np.random.normal(1, 0.04, size=len(df))
    ax3.scatter(y_jitter, df['osi'], alpha=0.3, s=20, color='darkblue')

    ax3.set_ylabel('OSI', fontsize=12, fontweight='bold')
    ax3.set_title('OSI Distribution (Violin + Strip)', fontsize=13, fontweight='bold')
    ax3.set_xticks([1])
    ax3.set_xticklabels(['All Units'])
    ax3.grid(True, alpha=0.3, axis='y')

    # 4. Statistics summary
    ax4 = axes[1, 1]
    ax4.axis('off')

    # Calculate statistics
    stats_text = f"""
    OSI DISTRIBUTION STATISTICS
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    Sample Size:
    • Total units: {len(df)}

    Central Tendency:
    • Mean:       {df['osi'].mean():.4f}
    • Median:     {df['osi'].median():.4f}
    • Mode:       {df['osi'].mode().values[0] if len(df['osi'].mode()) > 0 else 'N/A'}

    Spread:
    • Std Dev:    {df['osi'].std():.4f}
    • Variance:   {df['osi'].var():.4f}
    • Range:      {df['osi'].max() - df['osi'].min():.4f}
    • IQR:        {df['osi'].quantile(0.75) - df['osi'].quantile(0.25):.4f}

    Distribution:
    • Min:        {df['osi'].min():.4f}
    • Q1 (25%):   {df['osi'].quantile(0.25):.4f}
    • Q2 (50%):   {df['osi'].quantile(0.50):.4f}
    • Q3 (75%):   {df['osi'].quantile(0.75):.4f}
    • Max:        {df['osi'].max():.4f}

    Shape:
    • Skewness:   {df['osi'].skew():.4f}
    • Kurtosis:   {df['osi'].kurtosis():.4f}

    Selectivity Categories:
    • High (OSI > 0.5):   {(df['osi'] > 0.5).sum()} ({(df['osi'] > 0.5).sum()/len(df)*100:.1f}%)
    • Medium (0.3-0.5):   {((df['osi'] >= 0.3) & (df['osi'] <= 0.5)).sum()} ({((df['osi'] >= 0.3) & (df['osi'] <= 0.5)).sum()/len(df)*100:.1f}%)
    • Low (OSI < 0.3):    {(df['osi'] < 0.3).sum()} ({(df['osi'] < 0.3).sum()/len(df)*100:.1f}%)
    """

    ax4.text(0.05, 0.95, stats_text, transform=ax4.transAxes,
             fontsize=9, verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.3))

    plt.tight_layout()

    # Save figure
    if save_path is None:
        save_path = csv_path.parent / 'OSI_distribution.png'
    else:
        save_path = Path(save_path)

    fig.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"\nSaved OSI distribution plot to: {save_path}")

    plt.close(fig)

    return df


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description='Plot OSI distribution from tuning statistics CSV'
    )
    parser.add_argument(
        'csv_path',
        type=str,
        nargs='?',
        help='Path to tuning_statistics.csv file'
    )
    parser.add_argument(
        '--output', '-o',
        type=str,
        default=None,
        help='Output path for the plot (default: same folder as CSV)'
    )

    args = parser.parse_args()

    # If no CSV path provided, ask for input
    if args.csv_path is None:
        csv_path = input("Enter path to tuning_statistics.csv: ").strip().strip('"').strip("'")
    else:
        csv_path = args.csv_path

    try:
        df = plot_osi_distribution(csv_path, save_path=args.output)

        print("\n" + "="*60)
        print("OSI distribution analysis complete!")
        print("="*60)

    except FileNotFoundError:
        print(f"Error: CSV file not found at {csv_path}")
        print("Please check the file path and try again.")
    except Exception as e:
        print(f"Error during analysis: {e}")
        raise


if __name__ == "__main__":
    main()
